README: Installer et utiliser l'agent OpenAI (instructions)

1) Supprimer les anciennes versions du workflow
   - Si tu as .github/workflows/assistant-agent-v2.yml ou autres variantes, supprime-les pour éviter doublons.
     (ou garde uniquement la v1 et supprime la v2 si tu ne veux qu'une seule)

2) Créer le workflow
   - Crée le fichier .github/workflows/assistant-agent.yml (colle le YAML fourni).

3) Ajouter le secret OpenAI
   - Settings > Secrets and variables > Actions
   - New repository secret:
     - Name: OPENAI_API_KEY
     - Value: ta clé OpenAI (ne la partage pas)

4) Vérifier permissions Actions
   - Settings > Actions > General > Workflow permissions
   - Choisir "Read and write permissions" pour permettre au workflow de poster des commentaires.

5) Tester
   - Crée une branche test, modifie un fichier et ouvre une PR vers main.
   - Le workflow s'exécutera et postera son commentaire sur la PR si tout est en place.
   - Tu peux aussi lancer manuellement via Actions > assistant-agent > Run workflow.

6) Dépannage rapide
   - Si le workflow affiche "Skipping OpenAI analysis": soit il n'y a pas de diff, soit OPENAI_API_KEY est manquant.
   - Pour les erreurs 403 lors du POST: vérifie les permissions Actions (Read and write) et que tu utilises GITHUB_TOKEN fourni automatiquement.

7) Options avancées (à demander)
   - Restreindre l'analyse aux fichiers contenant "mois" ou "month".
   - Générer automatiquement un patch et ouvrir une PR (nécessite précautions).
   - Modifier le prompt système pour cibler la logique « mois ».

Ne partage jamais ta clé OPENAI_API_KEY publiquement.
