name: Deploy to Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload static site (dossier public)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
